git:
  commitPrefix:
    pattern: '^\w+\/(\w+-[0-9]+).*'
    replace: "$1: "

  paging:
    colorArg: always
    pager: delta --dark --paging=never

gui:
  branchColors:
    'develop': red

  authorColors:
    'Volker Wengert': green
